// Firebase configuration options
// Auto-generated by FlutterFire CLI on 2026-02-06
// Project: crackthecode
//
// SECURITY: API keys are loaded from environment variables.
// Build with: flutter build --dart-define-from-file=.env.json
// Or individual: --dart-define=FIREBASE_WEB_API_KEY=xxx

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Environment variable keys for Firebase configuration
class _FirebaseEnvKeys {
  // Web
  static const String webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
    defaultValue: '', // Will use fallback if not provided
  );
  static const String webAppId = String.fromEnvironment(
    'FIREBASE_WEB_APP_ID',
    defaultValue: '',
  );
  static const String webMeasurementId = String.fromEnvironment(
    'FIREBASE_WEB_MEASUREMENT_ID',
    defaultValue: '',
  );

  // Android
  static const String androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );
  static const String androidAppId = String.fromEnvironment(
    'FIREBASE_ANDROID_APP_ID',
    defaultValue: '',
  );

  // iOS/macOS
  static const String iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: '',
  );
  static const String iosAppId = String.fromEnvironment(
    'FIREBASE_IOS_APP_ID',
    defaultValue: '',
  );

  // Common
  static const String messagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '',
  );
  static const String projectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
    defaultValue: '',
  );
  static const String storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
    defaultValue: '',
  );
  static const String authDomain = String.fromEnvironment(
    'FIREBASE_AUTH_DOMAIN',
    defaultValue: '',
  );
}

/// Fallback values - used only in development when env vars not set
/// In production, always use --dart-define or .env.json
class _FirebaseFallbacks {
  static const String webApiKey = 'AIzaSyAXwks1YQWLlIHhUj8i5mP2viRxIkEvh5g';
  static const String webAppId = '1:145909045512:web:f20a260579e83a9b39f4bd';
  static const String webMeasurementId = 'G-K6WL6WEQBG';

  static const String androidApiKey = 'AIzaSyBxpKGo5XjRrGK6sT-EQycAYP-ohtwEcTs';
  static const String androidAppId = '1:145909045512:android:d12d557bbc3bbd5a39f4bd';

  static const String iosApiKey = 'AIzaSyCj1pFj5ZmrQUK3U8B0Ptj5b-laDAzRDyE';
  static const String iosAppId = '1:145909045512:ios:9945372cc2bdadce39f4bd';

  static const String messagingSenderId = '145909045512';
  static const String projectId = 'crackthecode';
  static const String storageBucket = 'crackthecode.firebasestorage.app';
  static const String authDomain = 'crackthecode.firebaseapp.com';
}

/// Helper to get value from env or fallback
String _getConfig(String envValue, String fallback) {
  return envValue.isNotEmpty ? envValue : fallback;
}

/// Default Firebase options for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.webApiKey, _FirebaseFallbacks.webApiKey),
    appId: _getConfig(_FirebaseEnvKeys.webAppId, _FirebaseFallbacks.webAppId),
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    authDomain: _getConfig(_FirebaseEnvKeys.authDomain, _FirebaseFallbacks.authDomain),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
    measurementId: _getConfig(_FirebaseEnvKeys.webMeasurementId, _FirebaseFallbacks.webMeasurementId),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.androidApiKey, _FirebaseFallbacks.androidApiKey),
    appId: _getConfig(_FirebaseEnvKeys.androidAppId, _FirebaseFallbacks.androidAppId),
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.iosApiKey, _FirebaseFallbacks.iosApiKey),
    appId: _getConfig(_FirebaseEnvKeys.iosAppId, _FirebaseFallbacks.iosAppId),
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
    iosBundleId: 'com.crackthecode.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.iosApiKey, _FirebaseFallbacks.iosApiKey),
    appId: _getConfig(_FirebaseEnvKeys.iosAppId, _FirebaseFallbacks.iosAppId),
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
    iosBundleId: 'com.crackthecode.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.webApiKey, _FirebaseFallbacks.webApiKey),
    appId: '1:145909045512:web:3355b9b1a29825a439f4bd',
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    authDomain: _getConfig(_FirebaseEnvKeys.authDomain, _FirebaseFallbacks.authDomain),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
    measurementId: 'G-EVQT4KPPYV',
  );

  // Linux uses web SDK - shares web configuration
  static FirebaseOptions get linux => FirebaseOptions(
    apiKey: _getConfig(_FirebaseEnvKeys.webApiKey, _FirebaseFallbacks.webApiKey),
    appId: _getConfig(_FirebaseEnvKeys.webAppId, _FirebaseFallbacks.webAppId),
    messagingSenderId: _getConfig(_FirebaseEnvKeys.messagingSenderId, _FirebaseFallbacks.messagingSenderId),
    projectId: _getConfig(_FirebaseEnvKeys.projectId, _FirebaseFallbacks.projectId),
    authDomain: _getConfig(_FirebaseEnvKeys.authDomain, _FirebaseFallbacks.authDomain),
    storageBucket: _getConfig(_FirebaseEnvKeys.storageBucket, _FirebaseFallbacks.storageBucket),
    measurementId: _getConfig(_FirebaseEnvKeys.webMeasurementId, _FirebaseFallbacks.webMeasurementId),
  );
}
